# Graph

## Node and Edge Fundamentals
DGL represents each node by a unique integer, called its `node ID`.

Each `edge` in DGL can be defined as tuple:($u$,$v$), which indicates that there is an edge that direction goes from node $u$ to node $v$.

Furthermore, DGL uses an expression of $(U,V)$ to describe an edge from the node-tensors. This could be described as $(U[i],V[i])$ which indicates the edges from $U[i]$ to $V[i]$.

In [2]:
import dgl
import torch 

# this suggests that the edges could be used from u(departure node tensor) to v(destination node tensor)
u,v = torch.tensor([0,0,0,1]),torch.tensor([1,2,3,3])

We use the function named `dgl.graph()` to create a garph as described in u and v.

In [3]:
g = dgl.graph((u,v))
print(g)

Graph(num_nodes=4, num_edges=4,
      ndata_schemes={}
      edata_schemes={})


We use the function `dgl.graph.nodes()` to get the unique nodeIDs for the graph.

In [4]:
# Node IDs
print(g.nodes())

tensor([0, 1, 2, 3])


Similarly, we use the function `dgl.graph.edges()` to get the edges.

In [5]:
# Edge end nodes
print(g.edges())
# combine information
print(g.edges(form='all'))

(tensor([0, 0, 0, 1]), tensor([1, 2, 3, 3]))
(tensor([0, 0, 0, 1]), tensor([1, 2, 3, 3]), tensor([0, 1, 2, 3]))


We can create graph with some nodes that are isolated.

In [6]:
# Create Isolated nodes
g = dgl.graph((u,v),num_nodes=8)

To create an `undirected graph`.

In [7]:
bg = dgl.to_bidirected(g)
bg.edges()

(tensor([0, 0, 0, 1, 1, 2, 3, 3]), tensor([1, 2, 3, 0, 3, 0, 0, 1]))

## Node and Edge Features
In this section we will discuss the issue that the users can store graph-specific properties of the nodes and edges. These features can be presented and accessed through `ndata` and `edata`.

In [9]:
# create an arbitrary graph with 6 nodes and 4 edges.
g = dgl.graph(([0,0,1,5],[1,2,2,0]))
g

Graph(num_nodes=6, num_edges=4,
      ndata_schemes={}
      edata_schemes={})

The following created an `ndata` feature called `x` and an `edata` feature called `x`.

In [13]:
g.ndata['x'] = torch.ones(g.num_nodes(),3) # this creates the node feature whose length is 3
g.edata['x'] = torch.ones(g.num_edges(),dtype=torch.int32) # this creates edge feature whose datatype is int32
g

Graph(num_nodes=6, num_edges=4,
      ndata_schemes={'x': Scheme(shape=(3,), dtype=torch.float32)}
      edata_schemes={'x': Scheme(shape=(), dtype=torch.int32)})

It is possible for user to develop such kind of feature to different degree.

In [16]:
g.ndata['y'] = torch.randn(g.num_nodes(),5)
g.ndata['x'][1]

tensor([1., 1., 1.])

`warning`

1. Each feature has unique name.
2. Feature should have numerical types.
3. A feature is created via tensor.
4. The same name of feature shared the same shape.

## Creating Graphs from External Sources

Creating a graph from a `SciPy` sparse matrix and a `NetworkX` graph.

In [18]:
import scipy.sparse as sp
spmat = sp.rand(100,100,density=0.05) # this creates a 5% nonzero entries
dgl.from_scipy(spmat) # the following shows the structure of the graph

Graph(num_nodes=100, num_edges=500,
      ndata_schemes={}
      edata_schemes={})

In [21]:
import networkx as nx 
nx_g = nx.path_graph(5) # a chain 0-1-2-3-4 undirected
dgl.from_networkx(nx_g) # from networks

Graph(num_nodes=5, num_edges=8,
      ndata_schemes={}
      edata_schemes={})

In [23]:
# the following code uses networkx to create directed graph
nxg = nx.DiGraph([(2,1),(1,2),(2,3),(0,0)])
dgl.from_networkx(nxg)

Graph(num_nodes=4, num_edges=4,
      ndata_schemes={}
      edata_schemes={})

The following shows how to load `csv` files into a graph.